name: Generate APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Android APK
        # هاد الأداة هي الرسمية والمستقرة 100%
        uses: pwa-builder/pwa-starter-action@v2.1.0
        with:
          url: 'https://dn-e-sport-clan-ff.vercel.app'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DN-CLAN-APP
          path: ./**/*.apk
          
